version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: spotify-db
    environment:
      POSTGRES_USER: spotify_user
      POSTGRES_PASSWORD: motdepassefort
      POSTGRES_DB: spotify_db
    volumes:
      - spotify-postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  spotify-postgres-data:
    driver: local